path: /home/drishtant/Desktop/Train_center/training_data  # dataset root dir
train: images/  # train images (relative to 'path')
val: images/  # val images (relative to 'path')

# Classes
names:
  0: Object